// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKxYUVCQ8dRRl0yHJ6swBEsWiOZs5uTzU',
    appId: '1:304624250459:web:8386cfb6f8dd28af20997e',
    messagingSenderId: '304624250459',
    projectId: 'projectmanager-dd4d0',
    authDomain: 'projectmanager-dd4d0.firebaseapp.com',
    storageBucket: 'projectmanager-dd4d0.appspot.com',
    measurementId: 'G-WFTMF781MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCL7qSSB-M8ZmGQ-ITfv6de66yAHjaEM',
    appId: '1:304624250459:android:8b419ec0469e40ab20997e',
    messagingSenderId: '304624250459',
    projectId: 'projectmanager-dd4d0',
    storageBucket: 'projectmanager-dd4d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFSafYeu9E7SoL8AQShUtkPnmPXziEoso',
    appId: '1:304624250459:ios:7ae4d0b56c4efa0320997e',
    messagingSenderId: '304624250459',
    projectId: 'projectmanager-dd4d0',
    storageBucket: 'projectmanager-dd4d0.appspot.com',
    iosClientId: '304624250459-h9m7te1m5sa5i2ug3tvq15vsnk2akv7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFSafYeu9E7SoL8AQShUtkPnmPXziEoso',
    appId: '1:304624250459:ios:7ae4d0b56c4efa0320997e',
    messagingSenderId: '304624250459',
    projectId: 'projectmanager-dd4d0',
    storageBucket: 'projectmanager-dd4d0.appspot.com',
    iosClientId: '304624250459-h9m7te1m5sa5i2ug3tvq15vsnk2akv7q.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKxYUVCQ8dRRl0yHJ6swBEsWiOZs5uTzU',
    appId: '1:304624250459:web:47de123eb4fd898420997e',
    messagingSenderId: '304624250459',
    projectId: 'projectmanager-dd4d0',
    authDomain: 'projectmanager-dd4d0.firebaseapp.com',
    storageBucket: 'projectmanager-dd4d0.appspot.com',
    measurementId: 'G-PZHL9FT7SC',
  );
}
